services:
  - type: web
    name: timemark-watermark
    env: node
    buildCommand: npm install && npm rebuild sharp
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_VERSION
        value: 20
    plan: free
